name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *" # 5분마다 실행
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping request
        run: curl https://coteach-vibe-shop-server.onrender.com
